---

- name: script
  hosts: dbservers
  connection: local
  tasks:
     - name: show vars
       debug:
         msg:
           - "Username {{ansible_user_id}}"
           - "Host {{inventory_hostname}} item {{item}}"
       loop: "{{ groups['webservers'] }}"
